# Generated by Django 4.0.6 on 2022-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateTimeField(verbose_name='%Y-%m-%d'),
        ),
    ]
